{{- if and .Values.gatewayApi.enabled .Values.gatewayApi.hostname }}
{{- $svcPort := .Values.service.port -}}
{{- range $host := .Values.gatewayApi.hostname }}
{{- $domain := $host | replace "." "-" | trimSuffix "-com" }}
{{- $name := printf "%s-%s" (include "app.fullname" $) $domain | trunc 63 | trimSuffix "-" }}

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ include "app.fullname" $ }}

spec:
  parentRefs:
    - name: {{ $name }}
      sectionName: {{ $.Values.gatewayRoute.sectionName | default "websecure" }}

  hostnames:
    - {{ $host | quote }}

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "app.fullname" $ }}
          port: {{ $svcPort }}

{{- end }}
{{- end }}
